### ISSUE TITLE
Make https://dfe-digital.github.io/ not a 404 page

### ISSUE THREAD

**Issue by david-mears-dfe** [DFE-Digital/technical-guidance#41]
When old documentation links to  https://dfe-digital.github.io/ , someone clicking the link and seeing the 404 will not have any clue that the guidance does still exist somewhere.

**Comment by saliceti** [comment]
The site was published at https://dfe-digital.github.io/technical-guidance/ which is set up to redirect to https://technical-guidance.education.gov.uk .
I'm not sure https://dfe-digital.github.io/ ever worked but I've now created https://github.com/DFE-Digital/dfe-digital.github.io to enable https://dfe-digital.github.io/ and set up to redirect to the tech guidance as well.

**Comment by david-mears-dfe** [comment]
Thanks! I don't remember where I found the erroneous link, but this redirect is nice to have.
