### ISSUE TITLE
Tool set info

### ISSUE THREAD

**Issue by aje54** [DFE-Digital/technical-guidance#81]
Need to publish a set of our "standard" tools including templates we uses (both ours and external ones e.g. from GDS) , favourite and useful gems, packages across not just Ruby but also .Net etc.

This will help us onboard supplier TA's more quickly, so we can say - please use x, y, z to implement functionality a,b,c

Perhaps split into areas:

Automation - pipeline tooling
Observability
Monitoring
Logging
Security 

etc.

**Comment by saliceti** [comment]
Now covered by https://technical-guidance.education.gov.uk/infrastructure/
